### ISSUE TITLE
allow user to create workspace at a disk root

### ISSUE THREAD

**Issue by eric-laporte** [UnitexGramLab/unitex-packaging-windows#3]
When the installer asked where it should create the user's personal workspace, I wanted it to be created directly at the root of disk D:\ so I selected D:\ but the installer did not allow me to go further in the installation and I must cancel.
Thanks

**Comment by martinec** [comment]
Thank you for your issue report. Could you please let me know if the installation was canceled/aborted with a specific message? Finally, if you could reproduce the problem, posting a screenshot in your reply can be a huge help.

**Comment by eric-laporte** [comment]
The installation was not canceled. When I selected D:\ as the directory where the installer would create the user's personal workspace, simply the "Install" option was greyed out, leaving me with the "< Back" and "Cancel" options (cf. attached image).
![installateur001](https://cloud.githubusercontent.com/assets/11441317/10133161/894868ac-65db-11e5-920a-d71481c5433f.gif)

**Comment by martinec** [comment]
It appear to be an issue related to administrator/non-administrator permissions. Would you please follow the next steps to check it and give me some feedback?
- Locate the Unitex-GramLab-3.1beta_win32-setup.exe icon in Windows Explorer.
- Right-click the setup icon, and then click Run as administrator.
- When the  User Account Control message is displayed, then click OK or YES.
- Try to select again D:\  as the user's personal workspace.

**Comment by eric-laporte** [comment]
Running the installer as administrator led to the same result. But 
Patrice discovered a way to select D:\ as the directory where the 
installer would create the user's personal workspace: by typing D:.\ 
instead of D:\ and it worked, even when I ran the installer as an 
ordinary user. I hope this information helps.
Thanks,
Eric

Le 29/09/2015 14:49, Cristian Martinez a écrit :

> It appear to be an issue related to administrator/non-administrator 
> permissions. Would you please follow the next steps to check it and 
> give me some feedback?
> - Locate the Unitex-GramLab-3.1beta_win32-setup.exe icon in Windows
>   Explorer.
> - Right-click the setup icon, and then click Run as administrator.
> - When the User Account Control message is displayed, then click OK
>   or YES.
> - Try to select D:\ as the directory where the installer would
>   create your user's personal workspace.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/UnitexGramLab/unitex-packaging-windows/issues/3#issuecomment-144048431.

## 

_ÉRIC LAPORTE_
Professeur
_LIGM_

_T_ : +33 1 60 95 75 52
BÂTIMENT COPERNIC - BUREAU 4B090
eric.laporte@univ-paris-est.fr
http://igm.univ-mlv.fr/~laporte/index_en.html 
http://igm.univ-mlv.fr/%7Elaporte/index_en.html

_UPEM - Université Paris-Est Marne-la-Vallée_
CITÉ DESCARTES - 5 BOULEVARD DESCARTES - CHAMPS-SUR-MARNE
77454 MARNE-LA-VALLÉE CEDEX 2 - WWW.U-PEM.FR http://www.u-pem.fr

**Comment by eric-laporte** [comment]
Thanks, the new version is OK.
Eric

Le 02/10/2015 10:38, Cristian Martinez a écrit :

> Closed #3 
> https://github.com/UnitexGramLab/unitex-packaging-windows/issues/3 
> via 7cda6cf 
> https://github.com/UnitexGramLab/unitex-packaging-windows/commit/7cda6cfed9333786346607c2f72db8e4a3c8f34a.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/UnitexGramLab/unitex-packaging-windows/issues/3#event-425044102.

## 

_ÉRIC LAPORTE_
Professeur
_LIGM_

_T_ : +33 1 60 95 75 52
BÂTIMENT COPERNIC - BUREAU 4B090
eric.laporte@univ-paris-est.fr
http://igm.univ-mlv.fr/~laporte/index_en.html 
http://igm.univ-mlv.fr/%7Elaporte/index_en.html

_UPEM - Université Paris-Est Marne-la-Vallée_
CITÉ DESCARTES - 5 BOULEVARD DESCARTES - CHAMPS-SUR-MARNE
77454 MARNE-LA-VALLÉE CEDEX 2 - WWW.U-PEM.FR http://www.u-pem.fr
